### ISSUE TITLE
listener event is not triggered when page zoom is greater than 100%

### ISSUE THREAD

**Issue by Pranav-Dakshina** [karl-run/react-bottom-scroll-listener#11]

**Comment by karl-run** [comment]
Good catch!

Interestingly the browser handles this for you, but when zoomed the values can be off by a few decimals, so simply rounding the scroll position to the nearest int fixed the problem.

Thanks.

**Comment by karl-run** [comment]
Published as version `2.1.4`

**Comment by Pranav-Dakshina** [comment]
Cool. Thanks @karl-run for the quick response! :bowing_man:

**Comment by linchen5913** [comment]
Hi @karl-run ,
even though it's updated at 2.1.4, I still encounter this problem at 5.0.0 when browser is at 80%.
Would you be able to look into it? Thanks in advance for considering this request.

**Comment by karl-run** [comment]
Hi. I tested in both Firefox and Chrome, both work correctly both at 80% and 200% zoom. Do you have any specific options you use that could help me reproduce? Feel free to open a new issue with more details.

**Comment by karl-run** [comment]
The demo has a offset of around 300px I think. If you set an offset (I don't think it has to be a lot, maybe like 10px), are you still able to reproduce the bug? :smile:

**Comment by karl-run** [comment]
Create a new issue, and I'll see if I'm able to figure something out when I get some time. :smile:

**Comment by linchen5913** [comment]
Thanks a lot, I'll try to send a pr when I'm available. Currently I had no choice but to turn to another package.

**Comment by karl-run** [comment]
PR would also be awesome if you could figure something out. :star_struck: If you run both root and `example` in dev mode you can use the example project for testing.
