### ISSUE TITLE
Consider leading:true on debounce

### ISSUE THREAD

**Issue by silverwind** [karl-run/react-bottom-scroll-listener#13]
Currently, there is a useless delay of `debounce` (default 200ms) before the first `onBottom` callback which could be avoided by enabling the [`leading` option](https://lodash.com/docs/4.17.11#debounce). This is especially noticeable when one specifies a high `debounce` like `1000`. I see no reason to not set this option, further callbacks can be debounced, but the first should not.

**Comment by karl-run** [comment]
That's a good point. I'd like not to change any default behaviour but there's no reason why it can't be a prop.

**Comment by iwikal** [comment]
@karl-run If there isn't any reason to ever want a leading delay, why not change the default behavior? It's hard to imagine well-written code breaking because of such a change.

**Comment by karl-run** [comment]
Bold of you to assume that most consumers of any library is well written code. :smile: 

But in any case, I'm more than happy to change the default behaviour and just release a new major version. Anyone want to make a PR?

**Comment by karl-run** [comment]
This should be fixed now.
