### ISSUE TITLE
useBottomScrollListener useEffect runs before ref has been set

### ISSUE THREAD

**Issue by erin-doyle** [karl-run/react-bottom-scroll-listener#19]
I've been trying to use the `useBottomScrollListener` hook but it seems that at the time the `useEffect` hooks runs and checks for `if (ref != null)` that the ref has not had a chance to finish being set on my container element.  I wonder if the `useEffect` hook needs to have added to its dependency array `containerRef.current` if that's possible.  `useEffect` needs to somehow wait or re-run after `containerRef.current` has been set but it seems it runs too quickly and has no way of running again once `containerRef.current` has been updated.

**Comment by karl-run** [comment]
Hmm... Are you able to provide some code that reproduces the error? I'm not seeing this issue in my usage.

**Comment by erin-doyle** [comment]
I am setting the ref on a 3rd party component so it's possible there are complications there and how long it takes that library to set the ref.  I can try to put together a codepen at some point.  This would probably work more reliably if the ref was stored with `useState` rather than `useRef` and the `useEffect` had the ref from state as one of its dependencies so it would be guaranteed to run once the ref was updated.  Though that might not be a preferred solution.

**Comment by karl-run** [comment]
I'd love to have a stab at this if you are able to provide some reproduction steps.

**Comment by erin-doyle** [comment]
Sorry, it's been so long since I ran into this and I ended up coding my own solution instead.  So there's not any more I can provide at this point.  Feel free to close if that's not enough to go on.
