### ISSUE TITLE
hi,i got a problem in chrome 61.0.3163.100

### ISSUE THREAD

**Issue by yoruponder** [karl-run/react-bottom-scroll-listener#2]
it works only in first time when scroll the page to bottom, when append the new data into list it does not work in the callback.

is any wrongs in (line 20-24)
```
 handleOnScroll() {
    if (document.body.scrollHeight - this.props.offset <= (document.body.scrollTop + window.innerHeight)) {
      this.props.onBottom();
    }
  }
```
document.body.scrollTop always in 0,
this problem is only occur in new version desktop chrome, i got no problem yet, and the code run perfect in mobile device

**Comment by karl-run** [comment]
I'm able to reproduce the issue. It seems to be an issue with Chrome 61, I'll have a look if there's a workaround/fix I can do on my side.

**Comment by yoruponder** [comment]
thanks 👍   it works very cool now :-D
