### ISSUE TITLE
Useless debounce

### ISSUE THREAD

**Issue by ARMATAV** [karl-run/react-bottom-scroll-listener#20]
The debounce blocks the firing of the first event, making it completely useless for it's intended purpose.

**Comment by karl-run** [comment]
I haven't observed the behaviour you are describing. Are you able to provide an reproduction example?

Also, have you tried setting `debounce={0}`? It literally disables the debounce completely.

**Comment by iwikal** [comment]
This is probably a duplicate of #13

**Comment by karl-run** [comment]
Good point iwikal. :) Closing as duplicate of #13
