### ISSUE TITLE
Leaving bottom state

### ISSUE THREAD

**Issue by heimdallexus** [karl-run/react-bottom-scroll-listener#21]
Hello. Is there any way that I can listen to another event like when I leave bottom scroll?

**Comment by karl-run** [comment]
Like you hit bottom, but then scroll away from the bottom again? That would certainly be possible, from a implementation perspective that would require the library to keep some kind of state whether or not the bottom is currently hit. Which is slightly more complicated when when the offset prop is used.

Interesting suggestion nonetheless!

**Comment by heimdallexus** [comment]
Yeap, that's about it.
Ended up using react-visibility-sensor too check if my last item is visible.
Thanks anyway Karl. Great job. :)

**Comment by heimdallexus** [comment]
Thanks again.
