### ISSUE TITLE
Reset ref after reloading component

### ISSUE THREAD

**Issue by phucproutt** [karl-run/react-bottom-scroll-listener#29]
Hello, 
I'm using this lib and I think it's light and useful but I have one problem. I implemented for a table using infinite scroll and I don't know if we have a way to reset the ref after reloading the table or not?

**Comment by karl-run** [comment]
Hmm... Are you saying the ref changes and the scroll listener stops working?

**Comment by phucproutt** [comment]
No it's not stops working but my problem is when you have a table with a filter, after filtering your table is reloaded but I don't want it to scroll to the position in the past before filtering(scrollTop must be 0 in this case), so how can I set scrollTop to 0?

**Comment by karl-run** [comment]
If you simply need to scroll the page to the top again you can use `window.scrollTo(0, 0)`.

**Comment by karl-run** [comment]
If you are scrolling inside a specific container you should be able to use `.scrollTo` on the ref as well.

**Comment by phucproutt** [comment]
<BottomScrollListener onBottom={props.onFetchMore} offset={200}>
                    {scrollRef => {
                        return (
                            <TableContainer
                                ref={scrollRef}
                                style={{
                                    height: height - actionHeight - 5,
                                    maxWidth: width
                                }}
                            >
                            </TableContainer>
                        );
                    }}
                </BottomScrollListener>

Maybe for this component, can you tell me how I can use the .scrollTo in this specific container?

**Comment by karl-run** [comment]
Invoking `scrollRef.current.scrollTo(0, 0)` at the appropriate moment (maybe after the loading is complete?) should do the trick.
