### ISSUE TITLE
onBottom not call when container too small to be scrallable

### ISSUE THREAD

**Issue by damienromito** [karl-run/react-bottom-scroll-listener#31]
Everything is fine, but if my container no need to be scroll (because height smaller than parent container), the trigger isn't call

Thank you for your work

**Comment by karl-run** [comment]
Hmm, yes. If the page doesn't have any scroll the scroll event will never be triggerd, thus the callback will never be invoked.

Do you expect it to be called at least once?

**Comment by damienromito** [comment]
Yes. I display a button to go to the next page when the page can be fully read (= scrolled to the bottom). Then I need this feedback to display it.
Then, it's depends on the size of the screen, it's a responsive issue

**Comment by karl-run** [comment]
I think this should to the trick for you, 8043161b23dd0d377178e87f3a90a85596f9f1f9.

Please try it out by adding the beta version of 4.1.0 (`yarn add react-bottom-scroll-listener@beta`) and trying out the new option in the hook.

**Comment by damienromito** [comment]
The option isn't available for the BottomScrollListener component ? 
Because the hooks does not works for me... (probably in my case)
Thank you for your time.

**Comment by karl-run** [comment]
I've added the prop to the component as well and released a new beta version.

**Comment by damienromito** [comment]
It's works ! Thank you ;)

**Comment by karl-run** [comment]
Cool. :) I've released it as stable.
