### ISSUE TITLE
Component specific container callback does not fire

### ISSUE THREAD

**Issue by strommj** [karl-run/react-bottom-scroll-listener#36]
I have downloaded your repo and tested this on your example web app. When scrolling to the bottom of the `inner-scroll-example` element, the alert dialog does not fire.

This is also reproduced in my own application.

I am currently using:
 - node v12.16.3
 - npm v6.14.4
 - React v17.0.0

**Comment by karl-run** [comment]
Might be something to do with React 17. I'll check it out tomorrow.

**Comment by karl-run** [comment]
Hmm, I've upgraded to react 17 and the example app still works here. What browser and browser version are you using?

**Comment by strommj** [comment]
Oh, sorry, It appears I mis-interpreted the functionality. I had thought the callback would fire when the viewport reaches the bottom of the visible element container, rather than having to scroll to the bottom of the container content.

It does appear to work in the above parameters, but I suppose that doesn't achieve the functionality that I get from the documentation and thus honestly I'm not sure what it's functionality should be. Even if it is the container content, and the content doesn't overflow, it doesn't appear to work as it should when I plug it into my own project.

Also I tested with the "hooks" implementation, and it does the same thing.

Unless, if I'm again off the mark here... I'm testing this instance on google chrome v86.0.4240.75 (official build, 64-bit)

**Comment by karl-run** [comment]
Not sure if I follow completely here. I'd love to understand you completely so I can make the documentation more clear.

>  I had thought the callback would fire when the viewport reaches the bottom of the visible element container

Do you mean that in the context of the "On bottom of specific container" feature in the docs, where you would provide a ref to a element, such as:


```
const scrollRef = useBottomScrollListener(callback);

<div ref={scrollRef}>Callback will be invoked when this container is scrolled to bottom.</div>
```

Which would give you this functionality:

![Example](https://github.com/karl-run/react-bottom-scroll-listener/raw/master/example_inner.gif)

It doesn't behave like you expect? Or do you mean that if that inner container doesn't overflow, onBottom should trigger?

**Comment by strommj** [comment]
Hopefully this illustrates my thoughts:

![ezgif com-crop](https://user-images.githubusercontent.com/33530655/96918021-7fe30d80-145e-11eb-8ec3-3e8be95f0578.gif)

**Comment by karl-run** [comment]
Aha, I see! You'd like the callback to be fired upon leaving the document viewport? That's definitely not something the this library does in its current state. Would be an interesting addition.

**Comment by karl-run** [comment]
I think maybe [this hook](https://github.com/olistic/react-use-visibility) does what you want?

**Comment by karl-run** [comment]
I'll close this issue. I'll make the documentation more clear as well.
