### ISSUE TITLE
notOnBottom properity

### ISSUE THREAD

**Issue by oubaydos** [karl-run/react-bottom-scroll-listener#47]
Hey, 
I used your npm package react-bottom-scroll-listener in order to hide my footer component until I reach the bottom, but the problem now is that **I need to re-hide it once I am no longer in bottom**, which I don’t see an easy way to do, without creating a scroll event. So Is there any possibility for you to add a ``notOnBottom ``property.
This is for a university project, and I would appreciate if you added this feature as soon as possible
Thanks.

**Comment by karl-run** [comment]
The most common use case for this library is to implement endless scrolling, having a `notOnBottom`-callback doesn't fit that well with the concept. It could of course be a standalone hook such as `useLeavingBottomListener` or something like that. Pull requests are welcome.

Honestly though I think in your specific scenario you are best of implementing it in your app. If you're at the bottom, any negative scroll direction is going to be "not bottom".

**Comment by karl-run** [comment]
A little friendly advice @oubaydos:

> This is for a university project, and I would appreciate if you added this feature as soon as possible

No one working on open source projects, no matter how small or big, is going to implement arbitrary features at your whim, especially not time sensitive things.

**Comment by oubaydos** [comment]
thank you, i really thought it would be a good feature to add, if  i had time i will try to work on it, 
Thanks
