### ISSUE TITLE
can we add support for react 18.3.1?

### ISSUE THREAD

**Issue by selva-tuva** [karl-run/react-bottom-scroll-listener#70]
can we update react version 18.1.0 to 18.3.0 ([LINK](https://github.com/facebook/react/blob/main/CHANGELOG.md))

<img width="1033" alt="Screenshot 2024-09-28 at 11 48 13 AM" src="https://github.com/user-attachments/assets/e25dcd71-8bc8-4579-84e6-f6fad9d764db">

**Comment by karl-run** [comment]
Any reason you're not getting React 18.3 to work?

I've updated the example project to use 18.3.1: https://karl-run.github.io/react-bottom-scroll-listener/

Works like expected, no warning is the console. What issues are you seeing?

**Comment by selva-tuva** [comment]
<img width="1300" alt="Screenshot 2024-10-04 at 9 06 47 AM" src="https://github.com/user-attachments/assets/8c7078b6-aea5-453b-86fb-ce826c69bea4">

I am facing warnings

**Comment by karl-run** [comment]
You're not on the nevest version of react-bottom-scroll-listener. You're on 5.0.0, newest is 5.1.0 (which added support for React 18 2 years ago).
