### ISSUE TITLE
Issue on 3840 x 2160 resolution

### ISSUE THREAD

**Issue by Deg5112** [karl-run/react-bottom-scroll-listener#9]
Hello,

I have noticed an issue for 3840 x 2160 resolution screens, where on `onBottom` callback prop will not fire. For resolutions below that, it appears to be fine. Are you able to replicate this, and if so, have a fix?

Thanks!

**Comment by Deg5112** [comment]
Disregard, boss is no longer experiencing issue

**Comment by karl-run** [comment]
One thing that is worth noting when using this library is that if all the content fits on the screen, which it might do if your users have very large viewports, is that there will never be any scroll event. No scroll event, no bottom to be hit.

Just something to keep in mind. 😄
